// <auto-generated />
namespace TourDuLich_GUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TourGroupCostValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TourGroupCostValue));
        
        string IMigrationMetadata.Id
        {
            get { return "202010090931371_TourGroupCost-Value"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
